services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: mydb
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    volumes:
      - mariadb-data:/var/lib/mysql

  minio:
    container_name: minio_server
    image: quay.io/minio/minio:RELEASE.2025-07-23T15-54-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: root1234
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  noc-service:
    build:
      context: ./DS-Lab-NOC
    container_name: noc-service
    ports:
      - "8081:8081"
    command: ["./mvnw", "spring-boot:run"]

  my-app:
    working_dir: /app
    build:
      context: ./katan
    container_name: my-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/mydb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      NOC_SERVICE_URL: http://noc-service:8081
      EXTERNAL_API_BASE_URL: http://noc-service:8081
    volumes:
      - ./katan/src:/app/src
      - ./katan/pom.xml:/app/pom.xml
      - ./katan/.mvn:/app/.mvn
      - ./katan/mvnw:/app/mvnw
      - maven-repo:/root/.m2
    command: ["./mvnw", "spring-boot:run"]
    depends_on:
      - mariadb
      - noc-service

volumes:
  mariadb-data:
  maven-repo:
  minio_data:
  minio_config:
